# Generated by Django 5.0.6 on 2024-07-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_purchases',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
